In [2]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b = np.insert(a, 3, 1, axis=1)
b

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [7, 8, 9, 1]])

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
b / a

array([2., 2., 2.])

In [4]:
6 / a

array([6., 3., 2.])

In [2]:
import numpy as np
a = 1234
l = []
l.append(a)
a = 456
l.append(a)
l

[1234, 456]