In [1]:
import numpy as np

In [2]:
np.random.rand(4, 4)

array([[0.47224046, 0.8270519 , 0.44129236, 0.22206656],
       [0.5074664 , 0.86769871, 0.57384904, 0.7106918 ],
       [0.17199031, 0.80143373, 0.19395878, 0.58309208],
       [0.1499052 , 0.04823772, 0.06536284, 0.79355621]])

In [3]:
randMat = np.mat(np.random.rand(4, 4))
randMat

matrix([[0.48965526, 0.08831666, 0.43028022, 0.5603797 ],
        [0.7239072 , 0.65842612, 0.25697713, 0.00824036],
        [0.20466265, 0.49911583, 0.4396873 , 0.80445524],
        [0.75599043, 0.40534206, 0.55824379, 0.26881444]])

In [4]:
randMat.I

matrix([[ 2.97874565,  1.94680463, -1.39554897, -2.09294664],
        [-1.76152181,  0.82157333,  1.20971831,  0.02673503],
        [-3.9579036 , -3.73096752,  0.81891288,  5.91446866],
        [ 2.49834334,  1.03419128,  0.39997453, -2.71676102]])

In [5]:
a = {'a': 123, 'b': 456}
a


{'a': 123, 'b': 456}

In [6]:
a['c'] = a.get('c', 0) + 1

In [7]:
a

{'a': 123, 'b': 456, 'c': 1}

In [8]:
import torch

In [9]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])