### ndarray属性
* ndarray.ndim

> array的维数(axex)

* ndarray.shape

> array的shape

* ndarray.size

> array中元素的数量，相当于shape所有分量的乘积

* ndarray.dtype

> array中元素的数据类型

* ndarray.itemsize

> array中数据元素的大小


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5).astype(np.float32)
a.ndim, a.shape, a.size, a.dtype, a.itemsize

(2, (3, 5), 15, dtype('float32'), 4)

### 创建ndarray

In [3]:
# 从List创建
a = np.array([1, 2, 3, 4], dtype=np.int)
print('array{0}{1}{2}'.format('\n', a, '\n'))

# 创建全是1的数组
a = np.ones((2, 3))
print('ones{0}{1}{2}'.format('\n', a, '\n'))

# 创建1全是0的数组
a = np.zeros((2, 3))
print('zeros{0}{1}{2}'.format('\n', a, '\n'))

# 创建对内存不进行初始化的数组
a = np.empty((2, 3))
print('empty{0}{1}{2}'.format('\n', a, '\n'))

# 创建含有指定元素的数字
a = np.full((2, 3), 111)
print('full{0}{1}{2}'.format('\n', a, '\n'))

# 创建对角元素全为1的矩阵
a = np.eye(3)
print('eye{0}{1}{2}'.format('\n', a, '\n'))

# 创建从0到10，步长为2的数组
a = np.arange(0, 10, 2)
print('arange{0}{1}{2}'.format('\n', a, '\n'))

# 创建0到10之间，均匀分布长度为5的数组
a = np.linspace(0, 10, 5)
print('linspace{0}{1}{2}'.format('\n', a, '\n'))

# 生成[0, 5)之间，shape为(2, 3)的随机整数
a = np.random.randint(0, 5, (2, 3))
print('randint{0}{1}{2}'.format('\n', a, '\n'))

# 生成(0, 1)之间的随机浮点数
a = np.random.random((2, 4))
print('random{0}{1}{2}'.format('\n', a, '\n'))

# 生成正态分布的随机数组
a = np.random.normal(loc=0, scale=1, size=(2, 3))
print('normal{0}{1}{2}'.format('\n', a, '\n'))

array
[1 2 3 4]

ones
[[1. 1. 1.]
 [1. 1. 1.]]

zeros
[[0. 0. 0.]
 [0. 0. 0.]]

empty
[[0. 0. 0.]
 [0. 0. 0.]]

full
[[111 111 111]
 [111 111 111]]

eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange
[0 2 4 6 8]

linspace
[ 0.   2.5  5.   7.5 10. ]

randint
[[4 0 0]
 [3 2 3]]

random
[[0.11228994 0.50129737 0.26839745 0.4957756 ]
 [0.65700567 0.91416251 0.81915295 0.73489913]]

normal
[[-0.66070718 -0.26062192 -0.52472106]
 [ 1.47088667 -1.72661961 -0.00743626]]



### ndarray常见操作
> ### reshape

In [4]:
# reshape
x = np.arange(15)
a = x.reshape(3 ,5)
# 如果只关心需要多少行或者多少列，其余维填-1即可
b = x.reshape(15, -1)
c = x.reshape(-1, 15)
print(a, '\n')
print(b, '\n')
print(c, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]] 



> ### 矩阵乘法

In [5]:
# 矩阵乘法
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
# element product
print(A * B, '\n')

# matrix product
print(A @ B, '\n')
print(A.dot(B), '\n')
print(np.matmul(A, B), '\n')

[[2 0]
 [0 4]] 

[[5 4]
 [3 4]] 

[[5 4]
 [3 4]] 

[[5 4]
 [3 4]] 



> ### 矩阵转置

In [6]:
a = np.arange(1, 7).reshape(2, -1)
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


> ### 矩阵求逆

In [7]:
import numpy.linalg as lg
A = np.array([[0, 1], [2, 3]])
invA = lg.inv(A)
print(invA, '\n')
print(A.dot(invA), '\n')

[[-1.5  0.5]
 [ 1.   0. ]] 

[[1. 0.]
 [0. 1.]] 



> ### 排序

In [8]:
x = np.arange(15)
np.random.shuffle(x)
print(x)
sx = np.argsort(x)
print(sx)
px = np.sort(x)
print(px)

[ 0 12  6  2 13  3  7  5  4  9  1 10  8 14 11]
[ 0 10  3  5  8  7  2  6 12  9 11 14  1  4 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


> ### 数组大小比较

In [19]:
x = np.arange(15).reshape(3, 5)
cn = np.count_nonzero(x<=3)
wh = np.where(x<=3)
ex = np.extract(x<=3, x)
print(cn)
print(wh)
print(ex)
print(np.any(x == 0))
print(np.all(x > 0))

print(np.argmax(x))
print(np.argmin(x))

4
(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
[0 1 2 3]
True
False
14
0


> ### 数组flatten

In [10]:
# flatten和ravel都可以将数组展开，但flatten返回的是数组的拷贝，而ravel返回的是数组的视图
x = np.arange(15).reshape(3, 5)
a = x.flatten()
print(x)
print(a)
print(x.ravel())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


> ### 数组拼接

In [11]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(np.vstack((A, B)))
print('\n')
print(np.hstack((A, B)))

[[1 1]
 [0 1]
 [2 0]
 [3 4]]


[[1 1 2 0]
 [0 1 3 4]]


> ### 数组split
### 

In [12]:
a = np.arange(24).reshape(2, 12)
print(a)
print('\n')
print(np.hsplit(a, 3))
print('\n')
print(np.hsplit(a, (3, 4)))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]


[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3],
       [15]]), array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21, 22, 23]])]


> ### deep copy

In [13]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
