### 在解释语言中，_代表上次的输出内容，例如：

In [84]:
a = 123
a

123

In [85]:
b = 3 + _
b

126

### pass关键字，会作为一个函数的place-holder，但不做任何的工作

In [86]:
def passtest():
    pass
passtest()

### \*和\**可用于函数形参解包

In [87]:
def star_test(a, b, c):
    print(a, b, c)
data = [1, 2, 3]
star_test(*data)

1 2 3


In [88]:
def star_test(a, b, c, d):
    print(a, b, c, d)
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
star_test(**data)

1 2 3 4


In [89]:
def fun(*args, **kwargs):
    print('args=', args)
    print('kwargs=', kwargs)

fun(1, 2, 3, 4, A='a', B='b', C='c', D='d')

args= (1, 2, 3, 4)
kwargs= {'A': 'a', 'B': 'b', 'C': 'c', 'D': 'd'}


In [90]:
a, b, *c = 0, 1, 2, 3
a, b, c

(0, 1, [2, 3])

### copy与deepcopy
#### copy只拷贝父对象，不会拷贝父对象的子对象
#### deepcopy完全拷贝父对象及其子对象

In [91]:
import copy
a = [1, 2, 3, 4, ['a', 'b']] #原始对象
 
b = a                       #赋值，传对象的引用
c = copy.copy(a)            #对象拷贝，浅拷贝
d = copy.deepcopy(a)        #对象拷贝，深拷贝
 
a.append(5)                 #修改对象a
a[4].append('c')            #修改对象a中的['a', 'b']数组对象
 
print( 'a = ', a )
print( 'b = ', b )
print( 'c = ', c )
print( 'd = ', d )

a =  [1, 2, 3, 4, ['a', 'b', 'c'], 5]
b =  [1, 2, 3, 4, ['a', 'b', 'c'], 5]
c =  [1, 2, 3, 4, ['a', 'b', 'c']]
d =  [1, 2, 3, 4, ['a', 'b']]


### function annotation

In [92]:
def f(ham: str, eggs: str = 'eggs') -> str:
     print("Annotations:", f.__annotations__)
     print("Arguments:", ham, eggs)
     return ham + ' and ' + eggs

f('spam')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam eggs


'spam and eggs'

### List常见操作

In [93]:
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [94]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [95]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [96]:
import numpy as np
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)
[[row[i] for row in matrix] for i in range(4)]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [97]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

In [98]:
a = [1, 2, 3, 4, 5]
del a[0]
a

[2, 3, 4, 5]

### set常见操作

In [99]:
a = set('abracadabra')
b = set('alacazam')
print(a, b)
print(a - b)
print(a | b)
print(a & b)
print(a ^ b)

{'c', 'a', 'b', 'd', 'r'} {'m', 'c', 'a', 'z', 'l'}
{'d', 'r', 'b'}
{'m', 'a', 'c', 'z', 'b', 'd', 'r', 'l'}
{'a', 'c'}
{'d', 'r', 'm', 'l', 'z', 'b'}


In [100]:
{x for x in 'abracadabra' if x not in 'abc'}

{'d', 'r'}

### dict常见操作

In [101]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [102]:
del tel['sape']
tel

{'jack': 4098, 'guido': 4127}

In [103]:
list(tel)

['jack', 'guido']

In [104]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [105]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)
set(knights)

gallahad the pure
robin the brave


{'gallahad', 'robin'}

In [106]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


In [107]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


### 面向对象编程
#### __init__(self, args) 构造函数
#### _ 单前导下划线为命名约定，表示仅供内部使用，作为对程序员的提醒
#### __双前导下划线在类中使用时，触发名称修饰

In [108]:
class Complex:
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart

x = Complex(3.0, -4.5)
x.r, x.i

(3.0, -4.5)

In [109]:
# 继承
class DerivedClassName(Complex):
    pass

In [110]:
# @property
class DataSet(object):
  @property
  def method_with_property(self):
      return 15
  def method_without_property(self):
      return 15

l = DataSet()
print(l.method_with_property)
print(l.method_without_property()) 

15
15


In [111]:
# @classmethod @ staticmethod
# @staticmethod不需要表示自身对象的self和自身类的cls参数，就跟使用函数一样。
# @classmethod也不需要self参数，但第一个参数需要是表示自身类的cls参数。
# 如果在@staticmethod中要调用到这个类的一些属性方法，只能直接类名.属性名或类名.方法名。
# 而@classmethod因为持有cls参数，可以来调用类的属性，类的方法，实例化对象等，避免硬编码。
class Foo(object):
    @classmethod
    def cls_fun(cls):
        return "hello world"
    @staticmethod
    def static_fun():
        return "hello python"

foo = Foo()
print(Foo.cls_fun())
# print(foo.cls_fun())
print(Foo.static_fun())


hello world
hello python


In [112]:
# getter setter
class Goods(object):

    def __init__(self):
        # 原价
        self.original_price = 100
        # 折扣
        self.discount = 0.8

    @property
    def price(self):
        # 实际价格 = 原价*折扣
        new_price = self.original_price*self.discount
        return new_price

    @price.setter
    def price(self,value):
        self.original_price = value

    @price.deleter
    def price(self):
        del self.original_price


obj = Goods()
# print(obj.price)
obj.price = 200
print(obj.price)
del obj.price  # 删除了类中的price属性若再次调用就会报错


160.0
