In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4])

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((3, 4), 111)

array([[111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.random.randint(0, 10, 10)

array([9, 9, 5, 6, 9, 1, 1, 9, 6, 8])

In [11]:
np.random.randint(0, 10, (3, 5))

array([[6, 8, 2, 6, 5],
       [9, 4, 2, 8, 6],
       [6, 3, 1, 8, 5]])

In [12]:
np.random.random(10)

array([0.04945072, 0.41226359, 0.01362464, 0.6965972 , 0.06399313,
       0.14505005, 0.39786695, 0.20612922, 0.76941321, 0.96632338])

In [13]:
np.random.normal(0, 1, (2, 2))

array([[-0.41988391,  2.76928707],
       [-0.22035875,  0.84525157]])

In [16]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a.shape

(3, 5)

In [18]:
a.ndim

2

In [22]:
a.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
a.reshape(-1, 15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [23]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

In [25]:
matrix[:, 1]

array([10, 25, 40])

In [26]:
matrix[:, 0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [27]:
import numpy.linalg as lg