### **导入package**

In [35]:
import torch
import numpy as np

### **直接从list创建**

In [41]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### **Tensor和ndarray相互转化**

In [56]:
np_array = np.array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [50]:
x_np.numpy()

array([[1, 2],
       [3, 4]])

### **reshape Tensor**

In [51]:
x = torch.arange(12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### **Tensor的属性**

In [52]:
print(x.shape)
print(x.numel())
print(x.dtype)
print(x.device)

torch.Size([3, 4])
12
torch.int64
cpu


### **创建常见类型的Tensor**

In [ ]:
zeros_x = torch.zeros((2, 3, 4))
ones_x = torch.ones((2, 3, 4))
randn_x = torch.randn(3, 4)
print(zeros_x)
print(ones_x)
print(randn_x)

### **从已有的Tensor创建**

In [49]:
zl_x = torch.zeros_like(x)
ol_x = torch.ones_like(x)
rl_x = torch.randn_like(x, dtype=torch.float)
print(zl_x)
print(ol_x)
print(rl_x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[-2.0427,  0.4876, -0.2978,  2.4372],
        [ 0.6115, -1.3396, -1.5349, -1.6119],
        [ 1.0172,  0.5386,  0.3517,  0.8298]])
